name: Publish Nuget .Net4

on:
  push:
    branches: [ "master" ]

  pull_request:
    branches: [ "master" ]

env:
  BASE_PATH: src
  SOLUTION_NAME: MPSTI.PlenoSoft.Core.Net4
  PROJECT_NAME: MPSTI.PlenoSoft.Core.Selenium.Net4
    
jobs:
  build:
    name: Build, Pack & Publish (On windows-latest)
    runs-on: windows-latest

    steps:
    - name: Checkout Git Source
      uses: actions/checkout@v3

    - name: Install NuGet.exe
      uses: NuGet/setup-nuget@v1.1.1
      with:
        nuget-api-key: ${{ secrets.NUGET_API_KEY }}
        nuget-version: 'latest'
  
    - name: Install MSBuild.exe
      uses: microsoft/setup-msbuild@v1.1

    - name: Restore Solution Packages
      run: nuget restore ${{ env.SOLUTION_FILE }}
      env:
        SOLUTION_FILE: ${{ format('{0}/{1}.sln', env.BASE_PATH, env.SOLUTION_NAME) }}
        PROJECT_FILE: ${{ format('{0}/{1}/{1}.csproj', env.BASE_PATH, env.PROJECT_NAME) }}

    - name: Build Solution (Release)
      run: msbuild ${{ env.SOLUTION_FILE }} /t:rebuild /p:Configuration=Release
      env:
        SOLUTION_FILE: ${{ format('{0}/{1}.sln', env.BASE_PATH, env.SOLUTION_NAME) }}
        PROJECT_FILE: ${{ format('{0}/{1}/{1}.csproj', env.BASE_PATH, env.PROJECT_NAME) }}

    - name: Create Package (Release)
      run: nuget pack ${{ env.PROJECT_FILE }} -Properties Configuration=Release
      env:
        SOLUTION_FILE: ${{ format('{0}/{1}.sln', env.BASE_PATH, env.SOLUTION_NAME) }}
        PROJECT_FILE: ${{ format('{0}/{1}/{1}.csproj', env.BASE_PATH, env.PROJECT_NAME) }}

    - name: Publish Package (nuget.org)
      run: nuget push ${{ env.PACKAGE_FILE }} -Source https://api.nuget.org/v3/index.json -SkipDuplicate
      env:
        PACKAGE_FILE: ${{ format('**/{0}*.nupkg', env.PROJECT_NAME) }}

# https://www.zup.com.br/blog/github-actions-variaveis-de-ambiente-e-secrets
# https://docs.github.com/pt/github-ae@latest/actions/learn-github-actions/environment-variables
# https://docs.github.com/en/actions/learn-github-actions/environment-variables  
